Apply new features
tsivarev/vk-community-app-example pull request #4
Opened 2017-12-07 16:32 UTC by unvir

2017-12-08 06:18 UTC, tsivarev requested changes

2017-12-08 06:18 UTC, tsivarev commented on app.js
> +          data.response.items.forEach(function(elem) {
elem -> photo

2017-12-08 06:18 UTC, tsivarev commented on app.js
> +            imgElem.photo_604 = elem.photo_604;
imgElem.photo_604 -> imgElem.photo604

2017-12-08 06:18 UTC, tsivarev commented on app.js
> +            imgElem.photoid = elem.id;
imgElem. photoid -> imgElem. photoId

2017-12-08 06:18 UTC, tsivarev commented on app.js
> +      if (app.getUrlParameter('viewer_device') == 1) {
Давай сделаем обозначение строкой вместо цифры. Так будет наглядней. И сделаем константу

2017-12-09 06:36 UTC, tsivarev requested changes

2017-12-09 06:36 UTC, tsivarev commented on app.js
> +    sessionStorage.setItem('photo604', event.target.photo604);
в sessionStorage или все хранить через _ или сделать тогда photoId, viewerId

2017-12-11 06:35 UTC, tsivarev requested changes

2017-12-11 06:35 UTC, tsivarev commented on README.md
> +https://mydomain.com/vk-community-app/?viewer_device=1
Давай сделаем viewer_device=mobile или is_mobile_view = 1

2017-12-11 06:35 UTC, tsivarev commented on README.md
> +![Страница установки](https://github.com/unvir/vk-community-app-example/blob/master/images/install.png)
unvir  ->  tsivarev

2017-12-11 06:35 UTC, tsivarev commented on app.js
> +            'attachments': 'photo' + sessionStorage.getItem('viewerId') +
Формирование аттачей лучше разбить на переменные:
var photoRawId = 'photo' +  sessionStorage.getItem('viewerId') + sessionStorage.getItem('photoId');
var appLink = 'https://vk.com/app' + app.appId + '_-' + app.groupId;


....
'attachments': photoRawId + ',' + appLink,
....


Так будет легче понять разработчикам как формируются аттачи.

2017-12-11 06:37 UTC, unvir commented on README.md
> +![Страница установки](https://github.com/unvir/vk-community-app-example/blob/master/images/install.png)
Картинок у тебя пока нет в репозитории)

2017-12-11 07:02 UTC, tsivarev approved these changes

2017-12-11 07:02 UTC, merged